name: 🧹 Terraform lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
    
    - uses: actions/checkout@v4

    - run: terraform fmt -recursive -check
      id: fmt
      continue-on-error: true

    - name: format and push formatted files back to repo
      if: ${{ steps.fmt.exitcode }} ==  3 # Terraform exits with code 3 if there are files to format
      run: |
        terraform fmt -recursive | xargs -I {} git add {}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Automatic linting and formatting [skip ci]"
        git push

