name: 🧹 Terraform lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
    
    - uses: actions/checkout@v4

    - name: format terraform files recursively
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        terraform fmt -recursive | xargs -I {} git add {}
        git commit -m "Automatic linting and formatting [skip ci]"
        git push
      continue-on-error: true

