name: 🌐 Validation

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.tftest.hcl'
  workflow_dispatch:
  release:
    types: [created]
  issue_comment:
      types: [created]  

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  TF_VAR_tenant_id: ${{ secrets.AZ_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

concurrency: 
  group: terraform-plan-apply-destroy
  cancel-in-progress: false


jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    name: 🔍 Check Changed Files
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        run: |
          BASE_REF=${{ github.event.before }}
          HEAD_REF=${{ github.sha }}

          if [ -z "$BASE_REF" ] || [ "$BASE_REF" == "0000000000000000000000000000000000000000" ]; then
            echo "Base ref not found, using HEAD^"
            BASE_REF=$(git rev-parse HEAD^)
          fi

          CHANGED_FILES=$(git diff --name-only $BASE_REF $HEAD_REF)
          echo "Changed files: $CHANGED_FILES"
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Validate File Definitions
        run: |
          KNOWN_FILES="variables.tf applications.tf app_role_assignment.tf application/ groups.tf group/ tfe.tf hashicorp/ group_membership.tf user_assigned_identities.tf role_assignment.tf user_assigned_identity/"
          IGNORED_FILES="README.md LICENSE terraform.tfstate plan.tfplan"
          for FILE in ${{ env.changed_files }}; do
            if echo "$IGNORED_FILES" | grep -q "$FILE"; then
              echo "Ignoring file: $FILE"
              continue
            fi
            if ! echo "$KNOWN_FILES" | grep -q "$FILE"; then
              echo "Error: Unknown file detected: $FILE"
              exit 1
            fi
          done

  application-test:
    needs: check-changed-files
    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'applications.tf') || contains(needs.check-changed-files.outputs.changed_files, 'app_role_assignment.tf') || contains(needs.check-changed-files.outputs.changed_files, 'application/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run application test
        run: terraform test -filter tests/application.tftest.hcl

  group-test:
    needs: check-changed-files
    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'groups.tf') || contains(needs.check-changed-files.outputs.changed_files, 'group/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run group test
        run: terraform test -filter tests/group.tftest.hcl

  tfe-test:
    needs: check-changed-files
    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'tfe.tf') || contains(needs.check-changed-files.outputs.changed_files, 'hashicorp/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run tfe test
        run: terraform test -filter tests/tfe.tftest.hcl

  user-assigned-identities-test:
    needs: check-changed-files
    if: contains(needs.check-changed-files.outputs.changed_files, 'variables.tf') || contains(needs.check-changed-files.outputs.changed_files, 'group_membership.tf') || contains(needs.check-changed-files.outputs.changed_files, 'user_assigned_identities.tf') || contains(needs.check-changed-files.outputs.changed_files, 'role_assignment.tf') || contains(needs.check-changed-files.outputs.changed_files, 'user_assigned_identity/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run user assigned identities test
        run: terraform test -filter tests/user_assigned_identities.tftest.hcl
